import { GoogleGenAI, PersonGeneration } from '@google/genai';
import { IImageProvider } from './IImageProvider.js';

/**
 * Image provider using Google Imagen 4 via AI Studio API
 * Uses Google's dedicated text-to-image model for realistic property images
 */
export class GeminiImageProvider implements IImageProvider {
  private client: GoogleGenAI | null = null;

  constructor() {
    const apiKey = process.env.GEMINI_API_KEY;

    if (apiKey) {
      try {
        this.client = new GoogleGenAI({
          apiKey: apiKey,
        });
        console.log('✅ Imagen 4 image provider initialized (AI Studio API)');
      } catch (error) {
        console.error('Failed to initialize Imagen provider:', error);
        console.log('⚠️  Imagen image provider initialization failed');
      }
    } else {
      console.log('⚠️  Imagen image provider not configured (missing GEMINI_API_KEY)');
    }
  }

  async generateImage(prompt: string): Promise<Buffer> {
    if (!this.client) {
      throw new Error(
        'Imagen provider not configured. Set GEMINI_API_KEY environment variable.'
      );
    }

    try {
      console.log('🖼️  Generating image with Imagen 4...');
      
      const response = await this.client.models.generateImages({
        model: 'models/imagen-4.0-generate-001',
        prompt: prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/jpeg',
          personGeneration: PersonGeneration.DONT_ALLOW,
          aspectRatio: '1:1',
          imageSize: '1K',
        },
      });

      if (!response?.generatedImages || response.generatedImages.length === 0) {
        throw new Error('No images generated by Imagen 4');
      }

      const imageBytes = response.generatedImages[0]?.image?.imageBytes;
      if (!imageBytes) {
        throw new Error('No image data returned from Imagen 4');
      }

      // Convert base64 to Buffer
      return Buffer.from(imageBytes, 'base64');
    } catch (error) {
      console.error('Imagen 4 image generation error:', error);
      
      // Provide helpful error messages for common issues
      if (error instanceof Error) {
        if (error.message.includes('SAFETY') || error.message.includes('blocked')) {
          throw new Error('Imagen 4 blocked the image generation due to safety filters. Try a different prompt.');
        }
        if (error.message.includes('QUOTA') || error.message.includes('quota') || error.message.includes('429')) {
          throw new Error('Imagen 4 API quota exceeded. Check your Google AI Studio quotas.');
        }
        if (error.message.includes('API key')) {
          throw new Error('Invalid GEMINI_API_KEY. Get a new key from https://aistudio.google.com/apikey');
        }
      }
      
      throw new Error(`Imagen 4 image generation failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  getProviderName(): string {
    return 'Imagen 4 (AI Studio)';
  }

  isConfigured(): boolean {
    return this.client !== null;
  }
}
